services:
  node:
    build:
      context: ./docker/node
    container_name: node
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    ports:
      - 3000:3000
      - 80:80
      - 8080:8080
    networks:
      - main_bridge

  mysql:
    build:
      context: ./docker/mysql
    container_name: mysql
    volumes:
      - ./docker/mysql/db/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nuxtdb
      MYSQL_PASSWORD: nuxtdb
      MYSQL_DATABASE: nuxt
    ports:
      - 3306:3306
    networks:
      - main_bridge

networks:
  main_bridge:
    driver: bridge